all:
	g++ -std=c++11 -g ej3.cpp -o ej3
	python c_linea.py --blue_player ./ej3 --red_player ./random_player --first azul --columns 3 --rows 3 --p 21 --c 3 --iterations 1
	
nico:
	g++ -std=c++11 -g grid.cpp -o grid
	g++ -std=c++11 -g ej3Nico.cpp -o ej3N

rm:
	rm ej3

